POST http://localhost:3000/auth/refresh
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NCwiZW1haWwiOiJsYXVyYUBnbWFpbC5jb20iLCJyb2wiOiJhZG1pbiIsImFjdGl2aXRpZXMiOlsid3JpdGVyIiwic2luZ2VyIiwiZGVzaWduZXIiXSwiaWF0IjoxNzYwNDkzOTMzLCJleHAiOjE3NjEwOTg3MzN9.i7oZPUoEhRvDVzBX5S2DvbBLF0ZR38DNh20qzbreCLA